AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pomodoro Telegram Bot - Walking Skeleton

Globals:
  Function:
    Timeout: 30
    Runtime: java21
    MemorySize: 512
    Architectures:
      - x86_64

Parameters:
  AdminChatId:
    Type: String
    Description: Telegram Chat ID of the authorized user
  TelegramBotToken:
    Type: String
    Description: Telegram Bot API token
    NoEcho: true
  GoogleClientId:
    Type: String
    Description: Google OAuth2 Client ID
  GoogleClientSecret:
    Type: String
    Description: Google OAuth2 Client Secret
    NoEcho: true
  GoogleRefreshToken:
    Type: String
    Description: Google OAuth2 Refresh Token (offline access)
    NoEcho: true
  GoogleDriveFolderId:
    Type: String
    Description: Google Drive folder ID for saving notes

Resources:
  SessionStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PomodoroBotState
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: chatId
          AttributeType: N
      KeySchema:
        - AttributeName: chatId
          KeyType: HASH

  # IAM Role for EventBridge Scheduler to invoke Lambda
  SchedulerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambda
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                # Constructed ARN to avoid circular dependency
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}-BotFunction-*"

  BotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ewc.exocortex.pomodoro.BotHandler::handleRequest
      CodeUri: .
      Description: Telegram bot handler for Pomodoro tracking
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: live
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionStateTable
        - Statement:
            - Effect: Allow
              Action:
                - scheduler:CreateSchedule
                - scheduler:DeleteSchedule
              Resource: !Sub "arn:aws:scheduler:${AWS::Region}:${AWS::AccountId}:schedule/default/pomodoro-*"
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource: !GetAtt SchedulerExecutionRole.Arn
      Environment:
        Variables:
          ADMIN_CHAT_ID: !Ref AdminChatId
          TELEGRAM_BOT_TOKEN: !Ref TelegramBotToken
          GOOGLE_CLIENT_ID: !Ref GoogleClientId
          GOOGLE_CLIENT_SECRET: !Ref GoogleClientSecret
          GOOGLE_REFRESH_TOKEN: !Ref GoogleRefreshToken
          GOOGLE_DRIVE_FOLDER_ID: !Ref GoogleDriveFolderId
          SCHEDULER_ROLE_ARN: !GetAtt SchedulerExecutionRole.Arn
      Events:
        TelegramWebhook:
          Type: HttpApi
          Properties:
            Path: /webhook
            Method: POST

Outputs:
  WebhookUrl:
    Description: URL for Telegram Webhook
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook"
